title: docs.digi-kunst.nrw
description: Informationen über Digi-Kunst.nrw
theme: just-the-docs

url: https://digi-kunst.github.io/

search_enabled: false

aux_links: #oben rechts
  GitHub: https://github.com/Digi-Kunst/
