title: docs.Digi-Kunst.nrw
description: Informationen über Digi-Kunst.nrw
theme: just-the-docs

url: https://digi-kunst.github.io/

aux_links: #oben rechts
  GitHub: https://github.com/Digi-Kunst/

# External navigation links
nav_external_links:
  - title: Digi-Kunst.nrw
    url: https://www.rsh-duesseldorf.de/musikhochschule/wir-ueber-uns/digi-kunstnrw/
    hide_icon: false # set to true to hide the external link icon - defaults to false